[workspace]
members = [
  "core",
  "device",
  "device-0",
  "device-1",
  "device-2",
  "device-3",
  "device-4",
  "device-5",
  "drv-dma",
  "drv-dmamux",
  "drv-i2c",
  "drv-i2c-master",
  "drv-spi",
  "drv-etc",
  "macros",
  "svd",
]

[package]
name = "drone-stm32"
version = "0.9.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
description = "Drone for STM32."
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/drone-os/drone-stm32"

[features]
default = []
stm32f100 = [
  "drone-stm32-core/stm32f100",
  "drone-stm32-device/stm32f100",
  "drone-stm32-drv-dma/stm32f100",
  "drone-stm32-drv-dmamux/stm32f100",
  "drone-stm32-drv-i2c/stm32f100",
  "drone-stm32-drv-i2c-master/stm32f100",
  "drone-stm32-drv-spi/stm32f100",
  "drone-stm32-drv-etc/stm32f100",
]
stm32f101 = [
  "drone-stm32-core/stm32f101",
  "drone-stm32-device/stm32f101",
  "drone-stm32-drv-dma/stm32f101",
  "drone-stm32-drv-dmamux/stm32f101",
  "drone-stm32-drv-i2c/stm32f101",
  "drone-stm32-drv-i2c-master/stm32f101",
  "drone-stm32-drv-spi/stm32f101",
  "drone-stm32-drv-etc/stm32f101",
]
stm32f102 = [
  "drone-stm32-core/stm32f102",
  "drone-stm32-device/stm32f102",
  "drone-stm32-drv-dma/stm32f102",
  "drone-stm32-drv-dmamux/stm32f102",
  "drone-stm32-drv-i2c/stm32f102",
  "drone-stm32-drv-i2c-master/stm32f102",
  "drone-stm32-drv-spi/stm32f102",
  "drone-stm32-drv-etc/stm32f102",
]
stm32f103 = [
  "drone-stm32-core/stm32f103",
  "drone-stm32-device/stm32f103",
  "drone-stm32-drv-dma/stm32f103",
  "drone-stm32-drv-dmamux/stm32f103",
  "drone-stm32-drv-i2c/stm32f103",
  "drone-stm32-drv-i2c-master/stm32f103",
  "drone-stm32-drv-spi/stm32f103",
  "drone-stm32-drv-etc/stm32f103",
]
stm32f107 = [
  "drone-stm32-core/stm32f107",
  "drone-stm32-device/stm32f107",
  "drone-stm32-drv-dma/stm32f107",
  "drone-stm32-drv-dmamux/stm32f107",
  "drone-stm32-drv-i2c/stm32f107",
  "drone-stm32-drv-i2c-master/stm32f107",
  "drone-stm32-drv-spi/stm32f107",
  "drone-stm32-drv-etc/stm32f107",
]
stm32l4x1 = [
  "drone-stm32-core/stm32l4x1",
  "drone-stm32-device/stm32l4x1",
  "drone-stm32-drv-dma/stm32l4x1",
  "drone-stm32-drv-dmamux/stm32l4x1",
  "drone-stm32-drv-i2c/stm32l4x1",
  "drone-stm32-drv-i2c-master/stm32l4x1",
  "drone-stm32-drv-spi/stm32l4x1",
  "drone-stm32-drv-etc/stm32l4x1",
]
stm32l4x2 = [
  "drone-stm32-core/stm32l4x2",
  "drone-stm32-device/stm32l4x2",
  "drone-stm32-drv-dma/stm32l4x2",
  "drone-stm32-drv-dmamux/stm32l4x2",
  "drone-stm32-drv-i2c/stm32l4x2",
  "drone-stm32-drv-i2c-master/stm32l4x2",
  "drone-stm32-drv-spi/stm32l4x2",
  "drone-stm32-drv-etc/stm32l4x2",
]
stm32l4x3 = [
  "drone-stm32-core/stm32l4x3",
  "drone-stm32-device/stm32l4x3",
  "drone-stm32-drv-dma/stm32l4x3",
  "drone-stm32-drv-dmamux/stm32l4x3",
  "drone-stm32-drv-i2c/stm32l4x3",
  "drone-stm32-drv-i2c-master/stm32l4x3",
  "drone-stm32-drv-spi/stm32l4x3",
  "drone-stm32-drv-etc/stm32l4x3",
]
stm32l4x5 = [
  "drone-stm32-core/stm32l4x5",
  "drone-stm32-device/stm32l4x5",
  "drone-stm32-drv-dma/stm32l4x5",
  "drone-stm32-drv-dmamux/stm32l4x5",
  "drone-stm32-drv-i2c/stm32l4x5",
  "drone-stm32-drv-i2c-master/stm32l4x5",
  "drone-stm32-drv-spi/stm32l4x5",
  "drone-stm32-drv-etc/stm32l4x5",
]
stm32l4x6 = [
  "drone-stm32-core/stm32l4x6",
  "drone-stm32-device/stm32l4x6",
  "drone-stm32-drv-dma/stm32l4x6",
  "drone-stm32-drv-dmamux/stm32l4x6",
  "drone-stm32-drv-i2c/stm32l4x6",
  "drone-stm32-drv-i2c-master/stm32l4x6",
  "drone-stm32-drv-spi/stm32l4x6",
  "drone-stm32-drv-etc/stm32l4x6",
]
stm32l4r5 = [
  "drone-stm32-core/stm32l4r5",
  "drone-stm32-device/stm32l4r5",
  "drone-stm32-drv-dma/stm32l4r5",
  "drone-stm32-drv-dmamux/stm32l4r5",
  "drone-stm32-drv-i2c/stm32l4r5",
  "drone-stm32-drv-i2c-master/stm32l4r5",
  "drone-stm32-drv-spi/stm32l4r5",
  "drone-stm32-drv-etc/stm32l4r5",
]
stm32l4r7 = [
  "drone-stm32-core/stm32l4r7",
  "drone-stm32-device/stm32l4r7",
  "drone-stm32-drv-dma/stm32l4r7",
  "drone-stm32-drv-dmamux/stm32l4r7",
  "drone-stm32-drv-i2c/stm32l4r7",
  "drone-stm32-drv-i2c-master/stm32l4r7",
  "drone-stm32-drv-spi/stm32l4r7",
  "drone-stm32-drv-etc/stm32l4r7",
]
stm32l4r9 = [
  "drone-stm32-core/stm32l4r9",
  "drone-stm32-device/stm32l4r9",
  "drone-stm32-drv-dma/stm32l4r9",
  "drone-stm32-drv-dmamux/stm32l4r9",
  "drone-stm32-drv-i2c/stm32l4r9",
  "drone-stm32-drv-i2c-master/stm32l4r9",
  "drone-stm32-drv-spi/stm32l4r9",
  "drone-stm32-drv-etc/stm32l4r9",
]
stm32l4s5 = [
  "drone-stm32-core/stm32l4s5",
  "drone-stm32-device/stm32l4s5",
  "drone-stm32-drv-dma/stm32l4s5",
  "drone-stm32-drv-dmamux/stm32l4s5",
  "drone-stm32-drv-i2c/stm32l4s5",
  "drone-stm32-drv-i2c-master/stm32l4s5",
  "drone-stm32-drv-spi/stm32l4s5",
  "drone-stm32-drv-etc/stm32l4s5",
]
stm32l4s7 = [
  "drone-stm32-core/stm32l4s7",
  "drone-stm32-device/stm32l4s7",
  "drone-stm32-drv-dma/stm32l4s7",
  "drone-stm32-drv-dmamux/stm32l4s7",
  "drone-stm32-drv-i2c/stm32l4s7",
  "drone-stm32-drv-i2c-master/stm32l4s7",
  "drone-stm32-drv-spi/stm32l4s7",
  "drone-stm32-drv-etc/stm32l4s7",
]
stm32l4s9 = [
  "drone-stm32-core/stm32l4s9",
  "drone-stm32-device/stm32l4s9",
  "drone-stm32-drv-dma/stm32l4s9",
  "drone-stm32-drv-dmamux/stm32l4s9",
  "drone-stm32-drv-i2c/stm32l4s9",
  "drone-stm32-drv-i2c-master/stm32l4s9",
  "drone-stm32-drv-spi/stm32l4s9",
  "drone-stm32-drv-etc/stm32l4s9",
]

[dependencies.drone-core]
version = "=0.9.0"
git = "https://github.com/drone-os/drone-core"
# path = "../drone-core"

[dependencies.drone-stm32-core]
version = "=0.9.0"
path = "core"

[dependencies.drone-stm32-device]
version = "=0.9.0"
path = "device"

[dependencies.drone-stm32-drv-dma]
version = "=0.9.0"
path = "drv-dma"

[dependencies.drone-stm32-drv-dmamux]
version = "=0.9.0"
path = "drv-dmamux"

[dependencies.drone-stm32-drv-i2c]
version = "=0.9.0"
path = "drv-i2c"

[dependencies.drone-stm32-drv-i2c-master]
version = "=0.9.0"
path = "drv-i2c-master"

[dependencies.drone-stm32-drv-spi]
version = "=0.9.0"
path = "drv-spi"

[dependencies.drone-stm32-drv-etc]
version = "=0.9.0"
path = "drv-etc"

[dev-dependencies.test]
version = "0.2"
git = "https://github.com/drone-os/drone-test"
