[workspace]
members = ["macros"]

[package]
name = "drone-cortex-m"
version = "0.9.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
edition = "2018"
repository = "https://github.com/drone-os/drone-cortex-m"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = [
    "arm",
    "cortex",
    "rtos",
    "bare-metal",
    "firmware",
]
categories = [
    "embedded",
    "asynchronous",
    "concurrency",
    "no-std",
    "hardware-support",
]
description = """
ARM® Cortex®-M platform crate for Drone, an Embedded Operating System.
"""

[badges]
maintenance = { status = "actively-developed" }

[features]
default = []
std = ["drone-core/std", "futures-preview/std"]
fpu = []
cortex_m3_r0p0 = []
cortex_m3_r1p0 = []
cortex_m3_r1p1 = []
cortex_m3_r2p0 = []
cortex_m3_r2p1 = []
cortex_m4_r0p0 = []
cortex_m4_r0p1 = []
cortex_m4f_r0p0 = []
cortex_m4f_r0p1 = []

[dependencies.drone-cortex-m-macros]
version = "=0.9.0"
path = "macros"

[dependencies.drone-core]
version = "0.9.0"
path = "../drone-core"

[dependencies]
futures-preview = { version = "0.3.0-alpha", default-features = false }
