[workspace]
members = ["macros"]

[package]
name = "drone-cortex-m"
version = "0.11.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
edition = "2018"
repository = "https://github.com/drone-os/drone-cortex-m"
homepage = "https://www.drone-os.com/"
documentation = "https://api.drone-os.com/drone-cortex-m/0.11/drone_cortex_m/"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = [
    "arm",
    "cortex",
    "rtos",
    "bare-metal",
    "firmware",
]
categories = [
    "embedded",
    "asynchronous",
    "concurrency",
    "no-std",
    "hardware-support",
]
description = """
ARM® Cortex®-M platform crate for Drone, an Embedded Operating System.
"""

[badges]
maintenance = { status = "actively-developed" }

[features]
default = []
std = ["drone-core/std", "futures/std"]
fpu = []

[dependencies.drone-cortex-m-macros]
version = "=0.11.0"
path = "macros"

[dependencies.drone-core]
version = "0.11.0"
path = "../drone-core"

[dependencies]
futures = { version = "0.3.0", default-features = false }
