[workspace]
members = ["macros"]

[package]
name = "drone-cortex-m"
version = "0.9.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
edition = "2018"
description = "Drone for ARM Cortex-M."
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/drone-os/drone-cortex-m"

[dependencies.drone-cortex-m-macros]
version = "=0.9.0"
path = "macros"

[dependencies.drone-core]
version = "0.9.0"
git = "https://github.com/drone-os/drone-core"
# path = "../drone-core"

[dependencies.futures-preview]
version = "0.2"
default-features = false

[dependencies.failure]
version = "0.1"
default-features = false
features = ["derive"]

[dev-dependencies.test]
version = "0.2"
git = "https://github.com/drone-os/drone-test"
