[package]
name = "drone-cortex-m-macros"
version = "0.7.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
description = "Drone for ARM Cortex-M. Procedural macros."
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/drone-os/drone-cortex-m"

[lib]
proc-macro = true

[dependencies]
failure = "0.1"
quote = "0.3"
Inflector = "0.11"

[dependencies.drone-macros-core]
version = "0.7"
path = "../../drone-core/macros-core"

[dependencies.syn]
version = "0.11"
features = ["full", "parsing", "printing"]

[dependencies.clippy]
version = "0.0"
optional = true
